# TASCA SPRINT 9  Feature Engineering

## NIVELL 2

### *Exercici 2*

Continua amb el conjunt de dades de tema esportiu que t'agradi i aplica l'anàlisi de components principals.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from pandas import DataFrame

In [2]:
import sklearn
from sklearn.decomposition import PCA

+ *Començo important el meu data set de tenis*

In [3]:
tenis_df = pd.read_csv('Match.csv')
tenis_df

match_id          round        date  avg_minutes_game  \
0        m_2019_A_0      1st Round  2019-01-14              4.81   
1        m_2019_A_1      1st Round  2019-01-14              3.95   
2        m_2019_A_2      1st Round  2019-01-14              4.86   
3        m_2019_A_3      1st Round  2019-01-14              4.43   
4        m_2019_A_4      1st Round  2019-01-14              4.37   
...             ...            ...         ...               ...   
10155  m_2000_W_122  Quarterfinals  2000-06-26              3.95   
10156  m_2000_W_123  Quarterfinals  2000-06-26              4.26   
10157  m_2000_W_124     Semifinals  2000-06-26              3.74   
10158  m_2000_W_125     Semifinals  2000-06-26              3.30   
10159  m_2000_W_126      The Final  2000-06-26              4.24   

       avg_seconds_point  avg_minutes_set       tournament  year  \
0                   46.8             43.3  Australian Open  2019   
1                   35.7             40.5  Australian Open  2019   
2                   42.3             43.8  Australian Open  2019   
3                   43.3             41.0  Australian Open  2019   
4                   39.7             43.7  Australian Open  2019   
...                  ...              ...              ...   ...   
10155               37.3             41.5        Wimbledon  2000   
10156               39.0             48.3        Wimbledon  2000   
10157               37.2             39.6        Wimbledon  2000   
10158               34.7             33.0        Wimbledon  2000   
10159               35.7             44.5        Wimbledon  2000   

       match_minutes  
0              173.0  
1              162.0  
2              175.0  
3              164.0  
4              131.0  
...              ...  
10155          166.0  
10156          145.0  
10157          198.0  
10158           99.0  
10159          178.0  

[10160 rows x 9 columns]

+ *I estudio els null values que pot contenir*

In [4]:
tenis_df.isnull().sum()

match_id              0
round                 0
date                  0
avg_minutes_game     46
avg_seconds_point    45
avg_minutes_set      82
tournament            0
year                  0
match_minutes        43
dtype: int64

+ *Em desfaig de les observacions que continguin algun null value*

In [5]:
tenis_df = tenis_df.dropna()
tenis_df

match_id          round        date  avg_minutes_game  \
0        m_2019_A_0      1st Round  2019-01-14              4.81   
1        m_2019_A_1      1st Round  2019-01-14              3.95   
2        m_2019_A_2      1st Round  2019-01-14              4.86   
3        m_2019_A_3      1st Round  2019-01-14              4.43   
4        m_2019_A_4      1st Round  2019-01-14              4.37   
...             ...            ...         ...               ...   
10155  m_2000_W_122  Quarterfinals  2000-06-26              3.95   
10156  m_2000_W_123  Quarterfinals  2000-06-26              4.26   
10157  m_2000_W_124     Semifinals  2000-06-26              3.74   
10158  m_2000_W_125     Semifinals  2000-06-26              3.30   
10159  m_2000_W_126      The Final  2000-06-26              4.24   

       avg_seconds_point  avg_minutes_set       tournament  year  \
0                   46.8             43.3  Australian Open  2019   
1                   35.7             40.5  Australian Open  2019   
2                   42.3             43.8  Australian Open  2019   
3                   43.3             41.0  Australian Open  2019   
4                   39.7             43.7  Australian Open  2019   
...                  ...              ...              ...   ...   
10155               37.3             41.5        Wimbledon  2000   
10156               39.0             48.3        Wimbledon  2000   
10157               37.2             39.6        Wimbledon  2000   
10158               34.7             33.0        Wimbledon  2000   
10159               35.7             44.5        Wimbledon  2000   

       match_minutes  
0              173.0  
1              162.0  
2              175.0  
3              164.0  
4              131.0  
...              ...  
10155          166.0  
10156          145.0  
10157          198.0  
10158           99.0  
10159          178.0  

[10078 rows x 9 columns]

+ *I comprovo que no en queda cap*

In [6]:
tenis_df.isnull().sum()

match_id             0
round                0
date                 0
avg_minutes_game     0
avg_seconds_point    0
avg_minutes_set      0
tournament           0
year                 0
match_minutes        0
dtype: int64

+ *Em desfaig de les columnes que no contenen variables numèriques excepte la variable "target" que serà "tournament"*

In [7]:
tenis_df.drop(['match_id', 'round','date', 'year'], axis = 1, inplace = True)

C:\Users\Enric\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [9]:
tenis_df

avg_minutes_game  avg_seconds_point  avg_minutes_set       tournament  \
0                  4.81               46.8             43.3  Australian Open   
1                  3.95               35.7             40.5  Australian Open   
2                  4.86               42.3             43.8  Australian Open   
3                  4.43               43.3             41.0  Australian Open   
4                  4.37               39.7             43.7  Australian Open   
...                 ...                ...              ...              ...   
10155              3.95               37.3             41.5        Wimbledon   
10156              4.26               39.0             48.3        Wimbledon   
10157              3.74               37.2             39.6        Wimbledon   
10158              3.30               34.7             33.0        Wimbledon   
10159              4.24               35.7             44.5        Wimbledon   

       match_minutes  
0              173.0  
1              162.0  
2              175.0  
3              164.0  
4              131.0  
...              ...  
10155          166.0  
10156          145.0  
10157          198.0  
10158           99.0  
10159          178.0  

[10078 rows x 5 columns]

+ *Divideixo el data set en feature set  i els labels corresponents*

In [10]:
X = tenis_df.drop('tournament', 1)
y = tenis_df['tournament']

+ *En el codi anterior he guardat el feature sets a la variable "X" i la serie dels corresponents labels a la variable "y"*


In [11]:
X

avg_minutes_game  avg_seconds_point  avg_minutes_set  match_minutes
0                  4.81               46.8             43.3          173.0
1                  3.95               35.7             40.5          162.0
2                  4.86               42.3             43.8          175.0
3                  4.43               43.3             41.0          164.0
4                  4.37               39.7             43.7          131.0
...                 ...                ...              ...            ...
10155              3.95               37.3             41.5          166.0
10156              4.26               39.0             48.3          145.0
10157              3.74               37.2             39.6          198.0
10158              3.30               34.7             33.0           99.0
10159              4.24               35.7             44.5          178.0

[10078 rows x 4 columns]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

+ *Perquè el PCA funcioni millor, és adequat estandaritzar el feature set*

In [12]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)


+ *Comprovo que ha funcionat el codi, imprimint X_train, convertint el array en un dataframe i li faig un "describe()"
   on puc veure que les mean són molt properes a zero i les standard deviations són = 1*

In [13]:
print(X)

[[ 0.86690329  1.01997251  0.40245857  0.58125372]
 [-0.12126791 -0.30028905  0.12602594  0.36966629]
 [ 0.92435511  0.48473133  0.45182154  0.61972417]
 ...
 [-0.36256553 -0.12187533  0.0371726   1.06213425]
 [-0.86814149 -0.41923153 -0.61441859 -0.84215264]
 [ 0.21195261 -0.30028905  0.52092969  0.67742983]]


In [16]:
np.mean(X),np.std(X)

(-4.1950082137056917e-16, 1.0)

In [14]:
tenis_stdscaler_train_df = DataFrame(X)
tenis_stdscaler_train_df

0         1         2         3
0      0.866903  1.019973  0.402459  0.581254
1     -0.121268 -0.300289  0.126026  0.369666
2      0.924355  0.484731  0.451822  0.619724
3      0.430270  0.603674  0.175389  0.408137
4      0.361327  0.175481  0.441949 -0.226626
...         ...       ...       ...       ...
10073 -0.121268 -0.109981  0.224752  0.446607
10074  0.234933  0.092221  0.896088  0.042668
10075 -0.362566 -0.121875  0.037173  1.062134
10076 -0.868141 -0.419232 -0.614419 -0.842153
10077  0.211953 -0.300289  0.520930  0.677430

[10078 rows x 4 columns]

In [15]:
tenis_stdscaler_train_df.describe()

0             1             2             3
count  1.007800e+04  1.007800e+04  1.007800e+04  1.007800e+04
mean  -7.430662e-16  7.709870e-16  6.599867e-16 -8.452920e-16
std    1.000050e+00  1.000050e+00  1.000050e+00  1.000050e+00
min   -4.659961e+00 -4.546536e+00 -3.872375e+00 -2.746440e+00
25%   -3.740559e-01 -2.527121e-01 -4.762023e-01 -6.498004e-01
50%    6.257790e-02  6.843265e-02  7.554817e-03 -9.197902e-02
75%    5.107020e-01  4.014716e-01  5.406749e-01  6.389594e-01
max    6.485691e+00  4.184103e+01  9.258175e+00  1.004498e+01

+ *I ara ja aplico el PCA sense especificar el número de components en el constructor.De tal manera que totes les 4 variables
  

In [17]:
pca = PCA()
pca_X = pca.fit_transform(X)

+ *Ara puc generar un array amb el mètode "pca.explained_variance_ratio_" que em donarà informació de la variance causada per 
   cadascun dels components principals*

In [18]:
explained_variance = pca.explained_variance_ratio_

In [19]:
explained_variance

array([0.7887537 , 0.12881363, 0.05929627, 0.0231364 ])

+ *I comprovem que el primer component principal és responsable del 78,87 % de la la variance.I el segon causa 
   el 12,88% de la variance en el data set*
   
   *De tal forma que podem dir que el 91,04 % de la informació de classificació ("tournament") continguda en el data set,
    és capturada pels 2 primers components principals*


+ *POCIÓ 2 : PCA fixant el número de components que volem*

In [20]:
pca = PCA(n_components = 2)
pca_2components_X = pca.fit_transform(X)

+ *I podem generar un nou DtaFrame que tindrà els components proncipals per tottes les observacions*

In [21]:
pca_2components_X_df = pd.DataFrame(data = pca_2components_X
             , columns = ['principal component 1', 'principal component 2'])

In [22]:
pca_2components_X_df

principal component 1  principal component 2
0                   1.433256               0.286977
1                   0.020981              -0.500171
2                   1.246166              -0.034838
3                   0.799992               0.105404
4                   0.407934               0.322407
...                      ...                    ...
10073               0.200009              -0.462891
10074               0.658320              -0.008651
10075               0.244102              -0.993916
10076              -1.369272               0.275111
10077               0.544281              -0.698818

[10078 rows x 2 columns]

In [23]:
explained_variance = pca.explained_variance_ratio_

In [24]:
explained_variance

array([0.7887537 , 0.12881363])

+ *Veiem que hem trobat els mateixos valors que abans*